version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Run Build step"
          command: .\build_win.ps1
      - run:
          name: "Compress build files"
          command: Compress-Archive -Path "./Build/*" "Build.zip"
      - store_artifacts:
          path: .\Build.zip